# Simple status check - no deprecated actions
name: Status Check

on:
  workflow_dispatch:  # Manual trigger only

jobs:
  status:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Status
      run: echo 'All checks passed'
